# Generated by Django 5.1 on 2024-10-29 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses_mate", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GroupUser",
        ),
    ]
