# Generated by Django 5.1 on 2024-10-22 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "expenses_mate",
            "0002_rename_balances_balance_rename_expenses_expense_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="balance",
            options={"verbose_name": "精算状況", "verbose_name_plural": "精算状況"},
        ),
        migrations.AlterModelOptions(
            name="expense",
            options={
                "verbose_name": "支出グループ",
                "verbose_name_plural": "支出グループ",
            },
        ),
        migrations.AlterModelOptions(
            name="expensegroup",
            options={"verbose_name": "費用", "verbose_name_plural": "費用"},
        ),
        migrations.AlterModelOptions(
            name="groupuser",
            options={
                "verbose_name": "グループユーザー",
                "verbose_name_plural": "グループユーザー",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "ユーザー", "verbose_name_plural": "ユーザー"},
        ),
        migrations.AlterModelTable(
            name="balance",
            table="Balance",
        ),
        migrations.AlterModelTable(
            name="expense",
            table="Expense",
        ),
        migrations.AlterModelTable(
            name="expensegroup",
            table="ExpenseGroup",
        ),
        migrations.AlterModelTable(
            name="groupuser",
            table="GroupUser",
        ),
        migrations.AlterModelTable(
            name="user",
            table="User",
        ),
    ]
